### ISSUE TITLE
Registratiesysteem uitwerken

### ISSUE THREAD

**Issue by aavroc** [aavroc/HuiswerkHeroes#3]
Registratie van docent (HBVB) / leerling waarin onderstaande onderdelen worden opgenomen in de database.  
- [x] Email adres
- [x] Wachtwoord
- [x] Rol (docent of leerling)

**Comment by DaveSchaatsbergen** [comment]
Alles werkt nu qua registreren. kan ook aangeven of je docent of leerling bent.

**Comment by DaveSchaatsbergen** [comment]
het is klaar
